apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysecret
  namespace: default
spec:
  encryptedData:
    foo: AgBvPPR8i1aw00uhY1z3ztQb93RukRydjVlpKRp4jC/lYwPUkgqFTznw6D72Lt+GcbIEYAwIeFtn0UdPrfubJiw4xfpf4khRMDjau9aZn7X7bVg8m4CoYJ3M9KQHXNCwy0UOINBJUUxrVw9m0PWgFZb4RpCkfpt4Wqv5i6tP3dorNesOEihM1oB5PX+lLSLaLsNrm9us0IZRv+Dyuk/uAUVnUGUyckHXWGxDQtaw2zHxZDZRAlu6OhN0AExd66c8WqoBZ4jyNGWkWCeC0LOnrS89vKkYPpRrPgwfjOUfb1XR89NkiT3uIYYP5Wcl4JQyK1NWWwAfplvcW3Jd/t1zAM6pxmJ7GeJlooW5v+4emDHre9Ng2dS6WtRVOc2Trptz0kV9XbrtYR+W3yQCsR0XC3TLdN6L5ZIR708V9HB+fGnteqgCnh5dyOMjk/MG333jQk67zfsVjBEciF20Fww6w45cx0dpu0MXAYQIXziRgSoo9XCucy7cq0pMKoA0RjtLJyhbBrNfamUjNgKKMgFPYzKlbv5OkV6ehjOcai8lVZMxS5K/oFM6Rs3fiI9nLXNafU0iuxahfMt+hrKFbV41GtvQ7qGzRCmk6nV86JcZxY5tHGiXCrjouB6sFZBpuz0VyPuMXpnzc376HgRg1xSn4yFq1bfWMazvVUuNBah2+HGJFYj4MS3+tZT8sahILGjsIgSa4cQ=
  template:
    metadata:
      name: mysecret
      namespace: default
